#!/usr/bin/env bash
#
# One-shot local setup for Admin Studio.
#
# Verifies the toolchain, installs every dependency tree (root, server,
# client), and creates server/.env with a freshly generated encryption key.
# Safe to re-run: an existing .env is never overwritten.
#
# This is the one script in scripts/ that isn't Node — it has to be able to
# report that Node is missing, which a Node script cannot do.
#
#   ./scripts/setup-local.sh                      # install + configure
#   ./scripts/setup-local.sh --with-local-admin   # also enable the Local Admin account
#   ./scripts/setup-local.sh --build              # also produce a client production build
#
# Afterwards: npm run dev   → client on :3000, proxy on :3001

set -euo pipefail

MIN_NODE_MAJOR=18

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

WITH_LOCAL_ADMIN=0
DO_BUILD=0
for arg in "$@"; do
  case "$arg" in
    --with-local-admin) WITH_LOCAL_ADMIN=1 ;;
    --build)            DO_BUILD=1 ;;
    -h|--help)          awk 'NR>1 && /^#/ { sub(/^# ?/, ""); print; next } NR>1 { exit }' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "Unknown option: $arg (try --help)" >&2; exit 1 ;;
  esac
done

step() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
warn() { printf '\033[33mwarning:\033[0m %s\n' "$1" >&2; }
die()  { printf '\033[31merror:\033[0m %s\n' "$1" >&2; exit 1; }

# ── 1. Node ──────────────────────────────────────────────────────────────────
# Homebrew's versioned node formulae (node@22 etc.) are keg-only: installed,
# but deliberately absent from PATH. Find one rather than claiming Node is
# missing when it is merely unlinked.
step "Checking Node.js"
if ! command -v node >/dev/null 2>&1; then
  for prefix in /opt/homebrew/opt /usr/local/opt; do
    for v in 24 22 20 18; do
      if [ -x "$prefix/node@$v/bin/node" ]; then
        PATH="$prefix/node@$v/bin:$PATH"
        export PATH
        warn "using keg-only $prefix/node@$v (not on your PATH by default)"
        break 2
      fi
    done
  done
fi

if ! command -v node >/dev/null 2>&1; then
  echo "Node.js $MIN_NODE_MAJOR+ is required but was not found." >&2
  echo >&2
  case "$(uname -s)" in
    Darwin) echo "  brew install node@22   # then re-run this script" >&2 ;;
    *)      echo "  See https://nodejs.org/ or use your distribution's package manager." >&2 ;;
  esac
  exit 1
fi

NODE_VERSION="$(node -v)"
NODE_MAJOR="$(printf '%s' "$NODE_VERSION" | sed 's/^v//' | cut -d. -f1)"
if [ "$NODE_MAJOR" -lt "$MIN_NODE_MAJOR" ]; then
  die "Node $NODE_VERSION found, but $MIN_NODE_MAJOR+ is required."
fi
# The client is CRA (react-scripts 5.0.1), which is unreliable on very new
# Node majors. Not fatal — just the first thing to suspect if the build fails.
if [ "$NODE_MAJOR" -gt 22 ]; then
  warn "Node $NODE_VERSION is newer than react-scripts 5.0.1 is tested against; node@22 is the safe choice."
fi
echo "Node $NODE_VERSION, npm $(npm -v)"

command -v openssl >/dev/null 2>&1 || die "openssl is required to generate the encryption key."

# ── 2. Dependencies ──────────────────────────────────────────────────────────
step "Installing dependencies (root, server, client)"
npm run install:all

# ── 3. server/.env ───────────────────────────────────────────────────────────
# DATA_DIR is deliberately left unset so it defaults to server/data. The
# committed .env.example points it at /data, which is correct for a container
# host and wrong for a laptop.
step "Configuring server/.env"
ENV_FILE="server/.env"
if [ -f "$ENV_FILE" ]; then
  echo "$ENV_FILE already exists — leaving it untouched."
else
  cat > "$ENV_FILE" <<EOF
# Local development config. Generated by scripts/setup-local.sh — gitignored.
PORT=3001

# DATA_DIR intentionally unset -> defaults to server/data (the json backend).

# AES-256-GCM key encrypting the stored credential registry.
# Losing it means every registered tenant must be registered again.
DATA_ENCRYPTION_KEY=$(openssl rand -hex 32)

# Registering a tenant DELETES every OAuth client on it that has this name,
# then creates a new one. Production uses the default
# ("identity-app-user-login"), so local dev must NOT: sharing it means each
# environment deletes the other's client on every registration, and the
# loser's sign-in fails (Safari saves the rejected response as a file named
# "authorize"). Keep this distinct from every deployed environment.
SP_SIGNIN_CLIENT_NAME=identity-app-user-login-dev
EOF
  echo "Created $ENV_FILE with a generated DATA_ENCRYPTION_KEY and a dev-only SP_SIGNIN_CLIENT_NAME."
fi

# An .env from before this was written by default has no client name, which
# silently falls back to production's. Add it rather than leave the collision.
if ! grep -q '^SP_SIGNIN_CLIENT_NAME=' "$ENV_FILE" 2>/dev/null; then
  cat >> "$ENV_FILE" <<'EOF'

# Added by setup-local.sh: keep local dev's OAuth client distinct from
# production's, or registering a tenant in one deletes the other's client.
SP_SIGNIN_CLIENT_NAME=identity-app-user-login-dev
EOF
  echo "Added a dev-only SP_SIGNIN_CLIENT_NAME to $ENV_FILE (it was falling back to production's)."
fi

# ── 4. Local admin (optional) ────────────────────────────────────────────────
# A break-glass account whose session can only manage the OAuth client
# registry — it cannot reach tenant data or the SailPoint API.
LOCAL_ADMIN_PW=""
if [ "$WITH_LOCAL_ADMIN" -eq 1 ]; then
  step "Enabling the Local Admin account"
  if grep -q '^LOCAL_ADMIN_USERNAME=' "$ENV_FILE" 2>/dev/null; then
    echo "Local admin is already configured — leaving the existing credentials alone."
  else
    LOCAL_ADMIN_PW="$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9')"
    cat >> "$ENV_FILE" <<EOF

# Local admin ("break-glass") account, enabled only when BOTH are set. Its
# session can do exactly one thing: manage the stored OAuth client registry.
LOCAL_ADMIN_USERNAME=admin
LOCAL_ADMIN_PASSWORD=$LOCAL_ADMIN_PW
EOF
    echo "Added credentials to $ENV_FILE."
  fi
fi

# ── 5. Production build (optional) ───────────────────────────────────────────
if [ "$DO_BUILD" -eq 1 ]; then
  step "Building the client for production"
  (cd client && npm run build)
  echo "Build output: client/build/"
fi

# ── Done ─────────────────────────────────────────────────────────────────────
step "Setup complete"
if [ -n "$LOCAL_ADMIN_PW" ]; then
  echo "Local Admin credentials (stored only in $ENV_FILE — save them now):"
  echo "    username: admin"
  echo "    password: $LOCAL_ADMIN_PW"
  echo
fi
cat <<'EOF'
Start the app with:

    npm run dev        # client → http://localhost:3000, proxy → http://localhost:3001

Sign-in needs an OAuth client registered for your ISC tenant; until then the
sign-in list is empty. Register one with:

    node scripts/register-oauth-client.js <tenant> <admin-client-id> <admin-client-secret>

Heads up: registration deletes and recreates the client named by
SP_SIGNIN_CLIENT_NAME (default "identity-app-user-login"). If a deployed
environment already uses that name on the same tenant, set
SP_SIGNIN_CLIENT_NAME in server/.env to something unique first, so local dev
gets its own client instead of taking over the shared one.
EOF
